// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9IWyYz1pg6PChiuytqid9poFqbsPFOqU',
    appId: '1:988206051976:web:02a46570d0f6af4b95e53d',
    messagingSenderId: '988206051976',
    projectId: 'burger-knight-d4d60',
    authDomain: 'burger-knight-d4d60.firebaseapp.com',
    storageBucket: 'burger-knight-d4d60.firebasestorage.app',
    measurementId: 'G-SJM8K2E3ZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBj0RU4IPcZQkRxgyLvW_UVVTyxqbnDnU',
    appId: '1:988206051976:android:38c99847bfdb371f95e53d',
    messagingSenderId: '988206051976',
    projectId: 'burger-knight-d4d60',
    storageBucket: 'burger-knight-d4d60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI48L8Lt52Eo22B3TF9IUNXpoEygci2P4',
    appId: '1:988206051976:ios:39505418d5492c9395e53d',
    messagingSenderId: '988206051976',
    projectId: 'burger-knight-d4d60',
    storageBucket: 'burger-knight-d4d60.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI48L8Lt52Eo22B3TF9IUNXpoEygci2P4',
    appId: '1:988206051976:ios:39505418d5492c9395e53d',
    messagingSenderId: '988206051976',
    projectId: 'burger-knight-d4d60',
    storageBucket: 'burger-knight-d4d60.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9IWyYz1pg6PChiuytqid9poFqbsPFOqU',
    appId: '1:988206051976:web:14dc3f2e9bf28e6b95e53d',
    messagingSenderId: '988206051976',
    projectId: 'burger-knight-d4d60',
    authDomain: 'burger-knight-d4d60.firebaseapp.com',
    storageBucket: 'burger-knight-d4d60.firebasestorage.app',
    measurementId: 'G-NQM0B7ST1R',
  );

}
